# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set environment variables
ENV PROJECT_ID=edemproject2
ENV TOPIC_ID=iotToBigQuery

# Create folder /app
RUN mkdir app

# Copy the current directory contents into the container at /app
COPY requirements.txt /app/
COPY generator_publisher.py /app/
COPY dataset.csv /app/

# Set the working directory to /app
WORKDIR /app

# Install requirements needed to execute Python script
RUN pip install -r requirements.txt

# Run the command to execute the Python script
CMD ["python", "generator_publisher.py", "--project_id", "${PROJECT_ID}", "--topic_id", "${TOPIC_ID}"]

